In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np

In [245]:
annotations = pd.read_csv('/content/drive/MyDrive/DATA VISUALIZATION/2016_dataset/segmentation_data/saved_states_0.csv',header=None,skiprows=None,nrows=100)
#annotations = pd.concat(chunk)
signal_data = pd.read_csv('/content/drive/MyDrive/DATA VISUALIZATION/2016_dataset/segmentation_data/0.csv',header=None,skiprows=None,nrows=100)
#singal_data = pd.concat(chunks)

In [232]:
signal_data.shape

(200, 73004)

In [233]:
annotations.shape

(200, 73004)

In [246]:
signal_data

,0,1,2,3,4,5,6,7,8,9,...,72994,72995,72996,72997,72998,72999,73000,73001,73002,73003
0,-69,-135,-104,-25,-63,-3,30,-22,26,77,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,297,728,779,802,590,242,187,134,139,97,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,-126,-306,-265,-310,-300,-332,-319,-341,-333,-331,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,350,703,599,638,591,574,529,525,496,515,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,-55,-97,-87,-125,-162,-247,-315,-410,-458,-493,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,251,520,402,367,350,290,208,272,66,215,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,-865,-1881,-1785,-1901,-1823,-1784,-1632,-1589,-1610,-1604,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,-47,-106,-92,-86,-85,-108,-105,-102,-148,-169,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,-100,-156,-36,48,89,72,23,-4,-62,-138,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,-13,-63,-25,-32,-20,-31,-31,-16,-20,-35,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [247]:
signal_temp = signal_data.drop(signal_data.iloc[:,16000:],axis=1)
temp = annotations.drop(annotations.iloc[:,16000:],axis=1)
temp

,0,1,2,3,4,5,6,7,8,9,...,15990,15991,15992,15993,15994,15995,15996,15997,15998,15999
0,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
1,3,3,3,3,3,3,3,3,3,3,...,4,4,4,4,4,4,4,4,4,4
2,4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4
3,4,4,4,4,4,4,4,4,4,4,...,2,2,2,2,2,2,2,2,2,2
4,1,1,1,1,1,1,1,1,1,1,...,3,3,3,3,3,3,3,3,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,2,2,2,2,2,2,2,2,2,2,...,4,4,4,4,4,4,4,4,4,4
87,1,1,1,1,1,1,1,1,1,1,...,4,4,4,4,4,4,4,4,4,4
88,2,2,2,2,2,2,2,2,2,2,...,4,4,4,4,4,4,4,4,4,4
89,1,1,1,1,1,1,1,1,1,1,...,2,2,2,2,2,2,2,2,2,2
90,1,1,1,1,1,1,1,1,1,1,...,2,2,2,2,2,2,2,2,2,2

In [248]:
temp = temp.replace(3,1)
temp = temp.replace(2,0)
temp = temp.replace(4,0)
temp

,0,1,2,3,4,5,6,7,8,9,...,15990,15991,15992,15993,15994,15995,15996,15997,15998,15999
0,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
1,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
87,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
88,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
89,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
90,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0

In [249]:
segmentation = temp.mul(signal_temp)
segmentation

,0,1,2,3,4,5,6,7,8,9,...,15990,15991,15992,15993,15994,15995,15996,15997,15998,15999
0,-69.0,-135.0,-104.0,-25.0,-63.0,-3.0,30.0,-22.0,26.0,77.0,...,-385.0,-351.0,-377.0,-301.0,-227.0,-264.0,-173.0,-66.0,-110.0,-9.0
1,297.0,728.0,779.0,802.0,590.0,242.0,187.0,134.0,139.0,97.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,0.0,0.0,0.0,0.0
4,-55.0,-97.0,-87.0,-125.0,-162.0,-247.0,-315.0,-410.0,-458.0,-493.0,...,2330.0,2775.0,3148.0,3432.0,3669.0,3864.0,4035.0,4181.0,4323.0,4433.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [238]:
data = pd.DataFrame()

In [250]:
data = data.append(segmentation)
data

,0,1,2,3,4,5,6,7,8,9,...,15990,15991,15992,15993,15994,15995,15996,15997,15998,15999
0,-69.0,-135.0,-104.0,-25.0,-63.0,-3.0,30.0,-22.0,26.0,77.0,...,-385.0,-351.0,-377.0,-301.0,-227.0,-264.0,-173.0,-66.0,-110.0,-9.0
1,297.0,728.0,779.0,802.0,590.0,242.0,187.0,134.0,139.0,97.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,0.0,0.0,0.0,0.0
4,-55.0,-97.0,-87.0,-125.0,-162.0,-247.0,-315.0,-410.0,-458.0,-493.0,...,2330.0,2775.0,3148.0,3432.0,3669.0,3864.0,4035.0,4181.0,4323.0,4433.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [251]:
labels = pd.read_csv('/content/drive/MyDrive/DATA VISUALIZATION/2016_dataset/segmentation_data/complete_labels_0.csv',header=None)

In [252]:
labels.iloc[:,0]

0      Abnormal
1      Abnormal
2      Abnormal
3      Abnormal
4      Abnormal
         ...
495      Normal
496      Normal
497      Normal
498      Normal
499      Normal
Name: 0, Length: 500, dtype: object

In [253]:
data2 = data

In [254]:
data2.insert(0,"label",labels.iloc[:,0])
data2

,label,0,1,2,3,4,5,6,7,8,...,15990,15991,15992,15993,15994,15995,15996,15997,15998,15999
0,Abnormal,-69.0,-135.0,-104.0,-25.0,-63.0,-3.0,30.0,-22.0,26.0,...,-385.0,-351.0,-377.0,-301.0,-227.0,-264.0,-173.0,-66.0,-110.0,-9.0
1,Abnormal,297.0,728.0,779.0,802.0,590.0,242.0,187.0,134.0,139.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Abnormal,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0
3,Abnormal,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,0.0,0.0,0.0,0.0
4,Abnormal,-55.0,-97.0,-87.0,-125.0,-162.0,-247.0,-315.0,-410.0,-458.0,...,2330.0,2775.0,3148.0,3432.0,3669.0,3864.0,4035.0,4181.0,4323.0,4433.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Abnormal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,Abnormal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,Abnormal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,Abnormal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,Abnormal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [255]:
data2.to_csv('/content/drive/MyDrive/DATA VISUALIZATION/2016_dataset/final_segmented_data/set0.csv',index=False)